# Use the official Nginx base image
FROM nginx:alpine

# Copy the custom index.html file to the Nginx HTML directory
COPY index.html /usr/share/nginx/html/index.html

# Expose port 8080 inside the container
EXPOSE 8080